//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCRControlCenter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VCRControlCenter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add Server {0}.
        /// </summary>
        internal static string AddServerTitle {
            get {
                return ResourceManager.GetString("AddServerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete Server {0}.
        /// </summary>
        internal static string DelServerTitle {
            get {
                return ResourceManager.GetString("DelServerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really hibernate Server {0}?.
        /// </summary>
        internal static string Hibernate {
            get {
                return ResourceManager.GetString("Hibernate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ignore until {0:HH:mm}.
        /// </summary>
        internal static string HibernateN {
            get {
                return ResourceManager.GetString("HibernateN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as configured (currently disabled until {0:HH:mm}).
        /// </summary>
        internal static string HibernateReset {
            get {
                return ResourceManager.GetString("HibernateReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibernate Confirmation.
        /// </summary>
        internal static string HibernateTitle {
            get {
                return ResourceManager.GetString("HibernateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid MultiCast Address.
        /// </summary>
        internal static string Multicast {
            get {
                return ResourceManager.GetString("Multicast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCR.NET Control Center (no Servers configured).
        /// </summary>
        internal static string NoServers {
            get {
                return ResourceManager.GetString("NoServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCR.NET Recording Service auf {0} (Port {1}).
        /// </summary>
        internal static string ServerTrayText {
            get {
                return ResourceManager.GetString("ServerTrayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are current or pending Recordings on this Computer - do you really want to shutdown the System?.
        /// </summary>
        internal static string ShutdownMessage {
            get {
                return ResourceManager.GetString("ShutdownMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown Confirmation.
        /// </summary>
        internal static string ShutdownTitle {
            get {
                return ResourceManager.GetString("ShutdownTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} on {1} ({2}).
        /// </summary>
        internal static string StationFormat {
            get {
                return ResourceManager.GetString("StationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (unavailable).
        /// </summary>
        internal static string StationUnavailable {
            get {
                return ResourceManager.GetString("StationUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update Language.
        /// </summary>
        internal static string UpdateLanguage {
            get {
                return ResourceManager.GetString("UpdateLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to modify Server {0}.
        /// </summary>
        internal static string UpdateServerTitle {
            get {
                return ResourceManager.GetString("UpdateServerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update Settings for local VCR.NET Recording Service.
        /// </summary>
        internal static string UpdateTitle {
            get {
                return ResourceManager.GetString("UpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
