//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JMS.DVB.Viewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JMS.DVB.Viewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the Audio Channel to hear:.
        /// </summary>
        internal static string AudioListHeadLine {
            get {
                return ResourceManager.GetString("AudioListHeadLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Multicast Address.
        /// </summary>
        internal static string BadMulticast {
            get {
                return ResourceManager.GetString("BadMulticast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the Station to show:.
        /// </summary>
        internal static string ChannelListHeadLine {
            get {
                return ResourceManager.GetString("ChannelListHeadLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to {0}.
        /// </summary>
        internal static string ConnectVCR {
            get {
                return ResourceManager.GetString("ConnectVCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio List [L].
        /// </summary>
        internal static string Context_Audio {
            get {
                return ResourceManager.GetString("Context_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel List [K].
        /// </summary>
        internal static string Context_Channels {
            get {
                return ResourceManager.GetString("Context_Channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show EPG Data [F1].
        /// </summary>
        internal static string Context_EPG {
            get {
                return ResourceManager.GetString("Context_EPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move in File.
        /// </summary>
        internal static string Context_FilePosition {
            get {
                return ResourceManager.GetString("Context_FilePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Full Screen Mode [J].
        /// </summary>
        internal static string Context_Fullscreen {
            get {
                return ResourceManager.GetString("Context_Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Settings [?].
        /// </summary>
        internal static string Context_Options {
            get {
                return ResourceManager.GetString("Context_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit [END].
        /// </summary>
        internal static string Context_Quit {
            get {
                return ResourceManager.GetString("Context_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Recording [#].
        /// </summary>
        internal static string Context_Record {
            get {
                return ResourceManager.GetString("Context_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Display [#].
        /// </summary>
        internal static string Context_Refresh {
            get {
                return ResourceManager.GetString("Context_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service List [M].
        /// </summary>
        internal static string Context_Service {
            get {
                return ResourceManager.GetString("Context_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change TimeShift [*].
        /// </summary>
        internal static string Context_TimeShift {
            get {
                return ResourceManager.GetString("Context_TimeShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videotext [F2].
        /// </summary>
        internal static string Context_VideoText {
            get {
                return ResourceManager.GetString("Context_VideoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Volume Control.
        /// </summary>
        internal static string Context_Volume {
            get {
                return ResourceManager.GetString("Context_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose Action:.
        /// </summary>
        internal static string ContextTitle {
            get {
                return ResourceManager.GetString("ContextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} until {1:HH:mm}.
        /// </summary>
        internal static string CurrentUntil {
            get {
                return ResourceManager.GetString("CurrentUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the Directory for Recordings..
        /// </summary>
        internal static string DirectoryDialogText {
            get {
                return ResourceManager.GetString("DirectoryDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Schedule ({{0}}%) - {0} of {1} Minutes.
        /// </summary>
        internal static string EPGPosition {
            get {
                return ResourceManager.GetString("EPGPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error occured.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Position ({0}%).
        /// </summary>
        internal static string FileTitle {
            get {
                return ResourceManager.GetString("FileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s on?.
        /// </summary>
        internal static string NameTitle {
            get {
                return ResourceManager.GetString("NameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Recording in {0}s.
        /// </summary>
        internal static string NextRecording {
            get {
                return ResourceManager.GetString("NextRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeshift and Multicast broadcasting not supported.
        /// </summary>
        internal static string NoMulticastTimeShift {
            get {
                return ResourceManager.GetString("NoMulticastTimeShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to do:.
        /// </summary>
        internal static string OptionListHeadLine {
            get {
                return ResourceManager.GetString("OptionListHeadLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use VCR.NET Profile {0}.
        /// </summary>
        internal static string OptionProfile {
            get {
                return ResourceManager.GetString("OptionProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use VCR.NET Profile {0} (active).
        /// </summary>
        internal static string OptionProfileActive {
            get {
                return ResourceManager.GetString("OptionProfileActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part {0}.
        /// </summary>
        internal static string PartialRecording {
            get {
                return ResourceManager.GetString("PartialRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Network.
        /// </summary>
        internal static string PlayStream {
            get {
                return ResourceManager.GetString("PlayStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Configuration has changed.
        /// </summary>
        internal static string PSIUpdate {
            get {
                return ResourceManager.GetString("PSIUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display reconfigured.
        /// </summary>
        internal static string PSIUpdateTitle {
            get {
                return ResourceManager.GetString("PSIUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently Recording ({0} kBytes).
        /// </summary>
        internal static string RecordingActive {
            get {
                return ResourceManager.GetString("RecordingActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording finished.
        /// </summary>
        internal static string RecordingFinished {
            get {
                return ResourceManager.GetString("RecordingFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Minutes (ends at {1:HH:mm}).
        /// </summary>
        internal static string RecordingItem {
            get {
                return ResourceManager.GetString("RecordingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording started.
        /// </summary>
        internal static string RecordingStarted {
            get {
                return ResourceManager.GetString("RecordingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose Recording Duration:.
        /// </summary>
        internal static string RecordingStartHeadLine {
            get {
                return ResourceManager.GetString("RecordingStartHeadLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string RecordingTitle {
            get {
                return ResourceManager.GetString("RecordingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really reset all Settings?.
        /// </summary>
        internal static string ResetSettings {
            get {
                return ResourceManager.GetString("ResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the Service to show:.
        /// </summary>
        internal static string ServiceListHeadLine {
            get {
                return ResourceManager.GetString("ServiceListHeadLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Quick Record Directory.
        /// </summary>
        internal static string SetDirectory {
            get {
                return ResourceManager.GetString("SetDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeshift.
        /// </summary>
        internal static string TimeShift {
            get {
                return ResourceManager.GetString("TimeShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume ({0}%).
        /// </summary>
        internal static string VolumeTitle {
            get {
                return ResourceManager.GetString("VolumeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation not available.
        /// </summary>
        internal static string Warning_NotAvailable {
            get {
                return ResourceManager.GetString("Warning_NotAvailable", resourceCulture);
            }
        }
    }
}
