//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JMS.DVB.CardServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JMS.DVB.CardServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for the previous command to finish.
        /// </summary>
        internal static string Exception_Busy {
            get {
                return ResourceManager.GetString("Exception_Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The electronic program guide (EPG) update is active.
        /// </summary>
        internal static string Exception_CollectionActive {
            get {
                return ResourceManager.GetString("Exception_CollectionActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The electronic program guide (EPG) update is not active.
        /// </summary>
        internal static string Exception_CollectionNotActive {
            get {
                return ResourceManager.GetString("Exception_CollectionNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to activate source &apos;{0}&apos; twice.
        /// </summary>
        internal static string Exception_DuplicateSource {
            get {
                return ResourceManager.GetString("Exception_DuplicateSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no device profile &apos;{0}&apos;.
        /// </summary>
        internal static string Exception_NoProfile {
            get {
                return ResourceManager.GetString("Exception_NoProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile &apos;{0}&apos; does not contain a source list.
        /// </summary>
        internal static string Exception_NoScan {
            get {
                return ResourceManager.GetString("Exception_NoScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source &apos;{0}&apos; is not active.
        /// </summary>
        internal static string Exception_NoSource {
            get {
                return ResourceManager.GetString("Exception_NoSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not an extension: {0}.
        /// </summary>
        internal static string Exception_NoSuchAction {
            get {
                return ResourceManager.GetString("Exception_NoSuchAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This instance is already using the device profile &apos;{0}&apos;.
        /// </summary>
        internal static string Exception_ProfileAttached {
            get {
                return ResourceManager.GetString("Exception_ProfileAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A source update (transponder scan) is already running.
        /// </summary>
        internal static string Exception_ScanActive {
            get {
                return ResourceManager.GetString("Exception_ScanActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no source update (transponder scan) active.
        /// </summary>
        internal static string Exception_ScanNotActive {
            get {
                return ResourceManager.GetString("Exception_ScanNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This instance is bound to the device profile &apos;{0}&apos; and not &apos;{1}&apos;.
        /// </summary>
        internal static string Exception_WrongProfile {
            get {
                return ResourceManager.GetString("Exception_WrongProfile", resourceCulture);
            }
        }
    }
}
