//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JMS.DVB.Algorithms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InterfaceResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InterfaceResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JMS.DVB.Algorithms.Properties.InterfaceResources", typeof(InterfaceResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetition Pattern contains Dublicates.
        /// </summary>
        internal static string Exception_BadPattern {
            get {
                return ResourceManager.GetString("Exception_BadPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Number of Sources must not be negative but is {0}.
        /// </summary>
        internal static string Exception_CILimitNegativ {
            get {
                return ResourceManager.GetString("Exception_CILimitNegativ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each Recording must have a positive Recording Duration but is {0}.
        /// </summary>
        internal static string Exception_Duration {
            get {
                return ResourceManager.GetString("Exception_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetition Pattern is empty.
        /// </summary>
        internal static string Exception_EmptyPattern {
            get {
                return ResourceManager.GetString("Exception_EmptyPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last Recording Day {1} must be at least the first Recording Day {0}.
        /// </summary>
        internal static string Exception_EndDay {
            get {
                return ResourceManager.GetString("Exception_EndDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a Day.
        /// </summary>
        internal static string Exception_EndNotDay {
            get {
                return ResourceManager.GetString("Exception_EndNotDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordings before 2000 can not be planned but is {0}.
        /// </summary>
        internal static string Exception_StartYear {
            get {
                return ResourceManager.GetString("Exception_StartYear", resourceCulture);
            }
        }
    }
}
