//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JMS.DVB.Algorithms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JMS.DVB.Algorithms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no Device Profile &apos;{0}&apos;.
        /// </summary>
        internal static string Exception_NoProfile {
            get {
                return ResourceManager.GetString("Exception_NoProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer change on {0} [{3}]: {1} (will free {2}).
        /// </summary>
        internal static string Trace_Optimizer_Report {
            get {
                return ResourceManager.GetString("Trace_Optimizer_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will now try to select Group {1} on Location {0}.
        /// </summary>
        internal static string Trace_Scanner_1stTune {
            get {
                return ResourceManager.GetString("Trace_Scanner_1stTune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second try to select Group {1} on Location {1} - DVB-C Spectrum Inversion changed.
        /// </summary>
        internal static string Trace_Scanner_2ndTune {
            get {
                return ResourceManager.GetString("Trace_Scanner_2ndTune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Group {1} on {0}.
        /// </summary>
        internal static string Trace_Scanner_DoneGroup {
            get {
                return ResourceManager.GetString("Trace_Scanner_DoneGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location {0} finished.
        /// </summary>
        internal static string Trace_Scanner_DoneLocation {
            get {
                return ResourceManager.GetString("Trace_Scanner_DoneLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} in NIT.
        /// </summary>
        internal static string Trace_Scanner_NIT {
            get {
                return ResourceManager.GetString("Trace_Scanner_NIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Group Information seen for Group {1} on Location {0}.
        /// </summary>
        internal static string Trace_Scanner_NoGroupInfo {
            get {
                return ResourceManager.GetString("Trace_Scanner_NoGroupInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Group {1} on {0}.
        /// </summary>
        internal static string Trace_Scanner_StartGroup {
            get {
                return ResourceManager.GetString("Trace_Scanner_StartGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staring Location {0}.
        /// </summary>
        internal static string Trace_Scanner_StartLocation {
            get {
                return ResourceManager.GetString("Trace_Scanner_StartLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Source {2} from Group {1} on {0}.
        /// </summary>
        internal static string Trace_Scanner_Station {
            get {
                return ResourceManager.GetString("Trace_Scanner_Station", resourceCulture);
            }
        }
    }
}
