//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JMS.DVB.Algorithms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SchedulerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SchedulerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JMS.DVB.Algorithms.Properties.SchedulerResources", typeof(SchedulerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}[{1}..{2}].
        /// </summary>
        internal static string Debug_DecryptionCounter {
            get {
                return ResourceManager.GetString("Debug_DecryptionCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}..{1}{2} on {3} {4}.
        /// </summary>
        internal static string Debug_ScheduleInformation {
            get {
                return ResourceManager.GetString("Debug_ScheduleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Rule must be of Format &lt;property&gt;:&lt;order&gt; but is &apos;{0}&apos;.
        /// </summary>
        internal static string Exception_BadScheduleFile {
            get {
                return ResourceManager.GetString("Exception_BadScheduleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is more than one Exception on {0}.
        /// </summary>
        internal static string Exception_DuplicateDate {
            get {
                return ResourceManager.GetString("Exception_DuplicateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording Plan has been startet, no more Resources can be added.
        /// </summary>
        internal static string Exception_HasPlanItems {
            get {
                return ResourceManager.GetString("Exception_HasPlanItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one Resource from a Decryption Group can not be resolved.
        /// </summary>
        internal static string Exception_IncompleteDecryption {
            get {
                return ResourceManager.GetString("Exception_IncompleteDecryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decyption Limit must not be negative but is {0}.
        /// </summary>
        internal static string Exception_NegativeEncryption {
            get {
                return ResourceManager.GetString("Exception_NegativeEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Limit must not be negative but is {0}.
        /// </summary>
        internal static string Exception_NegativeSourceLimit {
            get {
                return ResourceManager.GetString("Exception_NegativeSourceLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Source &apos;{0}&apos;.
        /// </summary>
        internal static string Exception_NoResourceForSource {
            get {
                return ResourceManager.GetString("Exception_NoResourceForSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Date is not a Date but {0}.
        /// </summary>
        internal static string Exception_NotAPureDate {
            get {
                return ResourceManager.GetString("Exception_NotAPureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Rule &apos;ByPriority:End&apos; missing.
        /// </summary>
        internal static string Exception_ResourcesNotTerminated {
            get {
                return ResourceManager.GetString("Exception_ResourcesNotTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; is not compatible with Order &apos;{1}&apos;.
        /// </summary>
        internal static string Exception_UnknownOrder {
            get {
                return ResourceManager.GetString("Exception_UnknownOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Rule can not use Property &apos;{0}&apos;.
        /// </summary>
        internal static string Exception_UnknownProperty {
            get {
                return ResourceManager.GetString("Exception_UnknownProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Device &apos;{1}&apos; with Priority {2} at Position {0} (-1 means append).
        /// </summary>
        internal static string Trace_AddResource {
            get {
                return ResourceManager.GetString("Trace_AddResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspecting Recording on Source &apos;{0}&apos; from {1} for {2}.
        /// </summary>
        internal static string Trace_Candidate {
            get {
                return ResourceManager.GetString("Trace_Candidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection best Plan out of {0:N0}.
        /// </summary>
        internal static string Trace_ChooseBestPlan {
            get {
                return ResourceManager.GetString("Trace_ChooseBestPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decryption planned for {0} starts late at {1}.
        /// </summary>
        internal static string Trace_CutEncrypted {
            get {
                return ResourceManager.GetString("Trace_CutEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decryption Allocation {0}.
        /// </summary>
        internal static string Trace_Decryption {
            get {
                return ResourceManager.GetString("Trace_Decryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports scheduling decisions..
        /// </summary>
        internal static string Trace_Description {
            get {
                return ResourceManager.GetString("Trace_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording must be discarded.
        /// </summary>
        internal static string Trace_Discarded {
            get {
                return ResourceManager.GetString("Trace_Discarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecordingScheduleAlgorithm.
        /// </summary>
        internal static string Trace_DisplayName {
            get {
                return ResourceManager.GetString("Trace_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will apply Exception to get {0}+{2} and {1}+{3}.
        /// </summary>
        internal static string Trace_Exception {
            get {
                return ResourceManager.GetString("Trace_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Source &apos;{1}&apos; on &apos;{0}&apos; from {2} for {3} (starts late).
        /// </summary>
        internal static string Trace_LateItem {
            get {
                return ResourceManager.GetString("Trace_LateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Task on &apos;{0}&apos; from {1} for {2} (starts late).
        /// </summary>
        internal static string Trace_LateTask {
            get {
                return ResourceManager.GetString("Trace_LateTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Source &apos;{1}&apos; on &apos;{0}&apos; from {2} for {3}.
        /// </summary>
        internal static string Trace_NormalItem {
            get {
                return ResourceManager.GetString("Trace_NormalItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Task on &apos;{0}&apos; from {1} for {2}.
        /// </summary>
        internal static string Trace_NormalTask {
            get {
                return ResourceManager.GetString("Trace_NormalTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0:N0} Alternative(s) to verify.
        /// </summary>
        internal static string Trace_PlanCount {
            get {
                return ResourceManager.GetString("Trace_PlanCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device &apos;{0}&apos; restarted, block until {1}.
        /// </summary>
        internal static string Trace_RestartResource {
            get {
                return ResourceManager.GetString("Trace_RestartResource", resourceCulture);
            }
        }
    }
}
