//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JMS.ChannelManagement.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JMS.ChannelManagement.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging incompatible Channel Files.
        /// </summary>
        internal static string BadMerge {
            get {
                return ResourceManager.GetString("BadMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create new Profile {0}.
        /// </summary>
        internal static string CreateProfileTitle {
            get {
                return ResourceManager.GetString("CreateProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete Profile {0}.
        /// </summary>
        internal static string DeleteErrorTitle {
            get {
                return ResourceManager.GetString("DeleteErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete Profile {0} permanently?.
        /// </summary>
        internal static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm.
        /// </summary>
        internal static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Common).
        /// </summary>
        internal static string FormatSystem {
            get {
                return ResourceManager.GetString("FormatSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string FormatUser {
            get {
                return ResourceManager.GetString("FormatUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (keep as is).
        /// </summary>
        internal static string NoISOSelection {
            get {
                return ResourceManager.GetString("NoISOSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Name.
        /// </summary>
        internal static string PostProcessingABC {
            get {
                return ResourceManager.GetString("PostProcessingABC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Receiver.
        /// </summary>
        internal static string PostProcessingLNB {
            get {
                return ResourceManager.GetString("PostProcessingLNB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels ({0}).
        /// </summary>
        internal static string PostProcessingRoot {
            get {
                return ResourceManager.GetString("PostProcessingRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Service.
        /// </summary>
        internal static string PostProcessingService {
            get {
                return ResourceManager.GetString("PostProcessingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources.
        /// </summary>
        internal static string PostProcessingTransponder {
            get {
                return ResourceManager.GetString("PostProcessingTransponder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update Profile {0}.
        /// </summary>
        internal static string SaveProfileTitle {
            get {
                return ResourceManager.GetString("SaveProfileTitle", resourceCulture);
            }
        }
    }
}
