//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JMS.DVB.Administration.Tools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JMS.DVB.Administration.Tools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to select {0}.
        /// </summary>
        internal static string Exception_Source_Title {
            get {
                return ResourceManager.GetString("Exception_Source_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Receiption on all Source Groups.
        /// </summary>
        internal static string SignalReport_Name {
            get {
                return ResourceManager.GetString("SignalReport_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal Reporter.
        /// </summary>
        internal static string SignalReport_ShortName {
            get {
                return ResourceManager.GetString("SignalReport_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Details on incoming Source Data.
        /// </summary>
        internal static string SourceStreams_Name {
            get {
                return ResourceManager.GetString("SourceStreams_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Streams.
        /// </summary>
        internal static string SourceStreams_ShortName {
            get {
                return ResourceManager.GetString("SourceStreams_ShortName", resourceCulture);
            }
        }
    }
}
