//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JMS.DVB.Administration.SourceScanner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JMS.DVB.Administration.SourceScanner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude Source Groups from Update.
        /// </summary>
        internal static string GroupExclude_Name {
            get {
                return ResourceManager.GetString("GroupExclude_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded Groups.
        /// </summary>
        internal static string GroupExclude_ShortName {
            get {
                return ResourceManager.GetString("GroupExclude_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Locations to update Sources (Transponder Scan).
        /// </summary>
        internal static string Location_Name {
            get {
                return ResourceManager.GetString("Location_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Locations.
        /// </summary>
        internal static string Location_ShortName {
            get {
                return ResourceManager.GetString("Location_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize Scan Locations.
        /// </summary>
        internal static string Optimizer_Long {
            get {
                return ResourceManager.GetString("Optimizer_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Optimizer.
        /// </summary>
        internal static string Optimizer_Short {
            get {
                return ResourceManager.GetString("Optimizer_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found: {0} Source(s) [{1} TV, {2} Radio, {3} Other] {4}.
        /// </summary>
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the full protocol in addition to the updated profile &apos;{0}&apos;?.
        /// </summary>
        internal static string Save_Profile {
            get {
                return ResourceManager.GetString("Save_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed.
        /// </summary>
        internal static string Save_Profile_Titel {
            get {
                return ResourceManager.GetString("Save_Profile_Titel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan for new or updated Sources (Transponder Scan).
        /// </summary>
        internal static string Scanner_Name {
            get {
                return ResourceManager.GetString("Scanner_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Update.
        /// </summary>
        internal static string Scanner_ShortName {
            get {
                return ResourceManager.GetString("Scanner_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix Properties of individual Sources.
        /// </summary>
        internal static string SourceModify_Name {
            get {
                return ResourceManager.GetString("SourceModify_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Properties.
        /// </summary>
        internal static string SourceModify_ShortName {
            get {
                return ResourceManager.GetString("SourceModify_ShortName", resourceCulture);
            }
        }
    }
}
