//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JMS.DVB.DirectShow.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JMS.DVB.DirectShow.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{1}&apos; is not a valid number ({0}).
        /// </summary>
        public static string Exception_BadNumber {
            get {
                return ResourceManager.GetString("Exception_BadNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The site does not support the method &apos;{0}&apos;.
        /// </summary>
        public static string Exception_NoMethod {
            get {
                return ResourceManager.GetString("Exception_NoMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The site does not support the property &apos;{0}&apos;.
        /// </summary>
        public static string Exception_NoProperty {
            get {
                return ResourceManager.GetString("Exception_NoProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site not defined.
        /// </summary>
        public static string Exception_NoSite {
            get {
                return ResourceManager.GetString("Exception_NoSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Machine not yet initialized.
        /// </summary>
        public static string Exception_NoState {
            get {
                return ResourceManager.GetString("Exception_NoState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method not called from UI Thread.
        /// </summary>
        public static string Exception_WrongThread {
            get {
                return ResourceManager.GetString("Exception_WrongThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digit 0.
        /// </summary>
        public static string InputKey_Digit0 {
            get {
                return ResourceManager.GetString("InputKey_Digit0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digit 1.
        /// </summary>
        public static string InputKey_Digit1 {
            get {
                return ResourceManager.GetString("InputKey_Digit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digit 2.
        /// </summary>
        public static string InputKey_Digit2 {
            get {
                return ResourceManager.GetString("InputKey_Digit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digit 3.
        /// </summary>
        public static string InputKey_Digit3 {
            get {
                return ResourceManager.GetString("InputKey_Digit3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digit 4.
        /// </summary>
        public static string InputKey_Digit4 {
            get {
                return ResourceManager.GetString("InputKey_Digit4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digit 5.
        /// </summary>
        public static string InputKey_Digit5 {
            get {
                return ResourceManager.GetString("InputKey_Digit5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digit 6.
        /// </summary>
        public static string InputKey_Digit6 {
            get {
                return ResourceManager.GetString("InputKey_Digit6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digit 7.
        /// </summary>
        public static string InputKey_Digit7 {
            get {
                return ResourceManager.GetString("InputKey_Digit7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digit 8.
        /// </summary>
        public static string InputKey_Digit8 {
            get {
                return ResourceManager.GetString("InputKey_Digit8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digit 9.
        /// </summary>
        public static string InputKey_Digit9 {
            get {
                return ResourceManager.GetString("InputKey_Digit9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string InputKey_Enter {
            get {
                return ResourceManager.GetString("InputKey_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Guide.
        /// </summary>
        public static string InputKey_Guide {
            get {
                return ResourceManager.GetString("InputKey_Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airing Details.
        /// </summary>
        public static string InputKey_Information {
            get {
                return ResourceManager.GetString("InputKey_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source List.
        /// </summary>
        public static string InputKey_List {
            get {
                return ResourceManager.GetString("InputKey_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line down.
        /// </summary>
        public static string InputKey_ListDown {
            get {
                return ResourceManager.GetString("InputKey_ListDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line up.
        /// </summary>
        public static string InputKey_ListUp {
            get {
                return ResourceManager.GetString("InputKey_ListUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string InputKey_Menu {
            get {
                return ResourceManager.GetString("InputKey_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute Sound.
        /// </summary>
        public static string InputKey_Mute {
            get {
                return ResourceManager.GetString("InputKey_Mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string InputKey_Off {
            get {
                return ResourceManager.GetString("InputKey_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page down.
        /// </summary>
        public static string InputKey_PageDown {
            get {
                return ResourceManager.GetString("InputKey_PageDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page up.
        /// </summary>
        public static string InputKey_PageUp {
            get {
                return ResourceManager.GetString("InputKey_PageUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Display.
        /// </summary>
        public static string InputKey_Pause {
            get {
                return ResourceManager.GetString("InputKey_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source down.
        /// </summary>
        public static string InputKey_SourceDown {
            get {
                return ResourceManager.GetString("InputKey_SourceDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source up.
        /// </summary>
        public static string InputKey_SourceUp {
            get {
                return ResourceManager.GetString("InputKey_SourceUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Text.
        /// </summary>
        public static string InputKey_Text {
            get {
                return ResourceManager.GetString("InputKey_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume down.
        /// </summary>
        public static string InputKey_VolumeDown {
            get {
                return ResourceManager.GetString("InputKey_VolumeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume up.
        /// </summary>
        public static string InputKey_VolumeUp {
            get {
                return ResourceManager.GetString("InputKey_VolumeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sequence.
        /// </summary>
        public static string RC_Learn_Add {
            get {
                return ResourceManager.GetString("RC_Learn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit without Saving.
        /// </summary>
        public static string RC_Learn_Cancel {
            get {
                return ResourceManager.GetString("RC_Learn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget all Sequences.
        /// </summary>
        public static string RC_Learn_Clear {
            get {
                return ResourceManager.GetString("RC_Learn_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Sequence.
        /// </summary>
        public static string RC_Learn_Delete1 {
            get {
                return ResourceManager.GetString("RC_Learn_Delete1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard Action.
        /// </summary>
        public static string RC_Learn_DeleteAll {
            get {
                return ResourceManager.GetString("RC_Learn_DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Directory: .
        /// </summary>
        public static string RC_Learn_Dir {
            get {
                return ResourceManager.GetString("RC_Learn_Dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration File: .
        /// </summary>
        public static string RC_Learn_File {
            get {
                return ResourceManager.GetString("RC_Learn_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Codes.
        /// </summary>
        public static string RC_Learn_KeyList {
            get {
                return ResourceManager.GetString("RC_Learn_KeyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Sequences.
        /// </summary>
        public static string RC_Learn_Mappings {
            get {
                return ResourceManager.GetString("RC_Learn_Mappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Exit.
        /// </summary>
        public static string RC_Learn_Save {
            get {
                return ResourceManager.GetString("RC_Learn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save Configuration.
        /// </summary>
        public static string RC_Learn_SaveError {
            get {
                return ResourceManager.GetString("RC_Learn_SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report all Calls to the Site.
        /// </summary>
        public static string Switch_Invoke_Description {
            get {
                return ResourceManager.GetString("Switch_Invoke_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LateBinding.
        /// </summary>
        public static string Switch_Invoke_Name {
            get {
                return ResourceManager.GetString("Switch_Invoke_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report all Input.
        /// </summary>
        public static string Switch_LogInputKeys_Description {
            get {
                return ResourceManager.GetString("Switch_LogInputKeys_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InputKey.
        /// </summary>
        public static string Switch_LogInputKeys_Name {
            get {
                return ResourceManager.GetString("Switch_LogInputKeys_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Number Composition.
        /// </summary>
        public static string Switch_LogNumber_Description {
            get {
                return ResourceManager.GetString("Switch_LogNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberComposer.
        /// </summary>
        public static string Switch_LogNumber_Name {
            get {
                return ResourceManager.GetString("Switch_LogNumber_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove Filter &apos;{0}&apos; from Graph: {1}.
        /// </summary>
        public static string Trace_Exception_RemoveFilter {
            get {
                return ResourceManager.GetString("Trace_Exception_RemoveFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method reports&apos;{0}&apos;.
        /// </summary>
        public static string Trace_Invoke_Action {
            get {
                return ResourceManager.GetString("Trace_Invoke_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; will be called.
        /// </summary>
        public static string Trace_Invoke_Method {
            get {
                return ResourceManager.GetString("Trace_Invoke_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; will be read.
        /// </summary>
        public static string Trace_Invoke_Property {
            get {
                return ResourceManager.GetString("Trace_Invoke_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution aborted: {0}.
        /// </summary>
        public static string Trace_LogInput_Aborted {
            get {
                return ResourceManager.GetString("Trace_LogInput_Aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution started: {0}.
        /// </summary>
        public static string Trace_LogInput_ActionList {
            get {
                return ResourceManager.GetString("Trace_LogInput_ActionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing State to &apos;{0}&apos;.
        /// </summary>
        public static string Trace_LogInput_EnterState {
            get {
                return ResourceManager.GetString("Trace_LogInput_EnterState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing &apos;{0}&apos;.
        /// </summary>
        public static string Trace_LogInput_Key {
            get {
                return ResourceManager.GetString("Trace_LogInput_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaving State &apos;{0}&apos;.
        /// </summary>
        public static string Trace_LogInput_LeaveState {
            get {
                return ResourceManager.GetString("Trace_LogInput_LeaveState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; checked for State &apos;{1}&apos;, currently using {2}.
        /// </summary>
        public static string Trace_LogInput_NextDigit {
            get {
                return ResourceManager.GetString("Trace_LogInput_NextDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State &apos;{0}&apos; starts to compose a Number.
        /// </summary>
        public static string Trace_LogInput_StartNumber {
            get {
                return ResourceManager.GetString("Trace_LogInput_StartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State &apos;{0}&apos; will further execute.
        /// </summary>
        public static string Trace_LogInput_State {
            get {
                return ResourceManager.GetString("Trace_LogInput_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number finished.
        /// </summary>
        public static string Trace_Number_Off {
            get {
                return ResourceManager.GetString("Trace_Number_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number is being composed.
        /// </summary>
        public static string Trace_Number_On {
            get {
                return ResourceManager.GetString("Trace_Number_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter &apos;{0}&apos; will be removed from the Graph.
        /// </summary>
        public static string Trace_RemoveFilter {
            get {
                return ResourceManager.GetString("Trace_RemoveFilter", resourceCulture);
            }
        }
    }
}
