//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JMS.DVBVCR.RecordingService.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JMS.DVBVCR.RecordingService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültige Dauer.
        /// </summary>
        internal static string BadDuration {
            get {
                return ResourceManager.GetString("BadDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Name enthält ungültige Zeichen.
        /// </summary>
        internal static string BadName {
            get {
                return ResourceManager.GetString("BadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Aufzeichnungstage sind ungültig.
        /// </summary>
        internal static string BadRepeat {
            get {
                return ResourceManager.GetString("BadRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Einlesen der Regeldatei für die Aufzeichnungsplanung: {0}.
        /// </summary>
        internal static string BadRuleFile {
            get {
                return ResourceManager.GetString("BadRuleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wird versucht, die Aufzeichnung &apos;{1}&apos; ({0}) mehrfach zu starten.
        /// </summary>
        internal static string BadScheduleInformation {
            get {
                return ResourceManager.GetString("BadScheduleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Aufzeichnungsoptionen sind ungültig.
        /// </summary>
        internal static string BadStreams {
            get {
                return ResourceManager.GetString("BadStreams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine Quelle ist ungültig.
        /// </summary>
        internal static string BadTVStation {
            get {
                return ResourceManager.GetString("BadTVStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die eindeutige Kennung ist ungültig.
        /// </summary>
        internal static string BadUniqueID {
            get {
                return ResourceManager.GetString("BadUniqueID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufwecksignal kann nicht angelegt werden.
        /// </summary>
        internal static string CreateWaitableTimer {
            get {
                return ResourceManager.GetString("CreateWaitableTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Endzeitpunkt darf nicht vor dem Startzeitpunkt liegen.
        /// </summary>
        internal static string EndsBeforeStart {
            get {
                return ResourceManager.GetString("EndsBeforeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datei &apos;{0}&apos; zur Programmzeitschrift kann nicht gelöscht werden.
        /// </summary>
        internal static string EPGDeleteDenied {
            get {
                return ResourceManager.GetString("EPGDeleteDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datei &apos;{0}&apos; zur Programmzeitschrift ist ungültig.
        /// </summary>
        internal static string EPGFileCorrupted {
            get {
                return ResourceManager.GetString("EPGFileCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Aktualisieren der Programmzeitschrift: {0}.
        /// </summary>
        internal static string EPGMergeFailed {
            get {
                return ResourceManager.GetString("EPGMergeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Rechner kann nicht in den Schlafzustand versetzt werden.
        /// </summary>
        internal static string HibernateFailed {
            get {
                return ResourceManager.GetString("HibernateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Rechner wird in den Schlafzustand versetzt.
        /// </summary>
        internal static string Hibernating {
            get {
                return ResourceManager.GetString("Hibernating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Schlafzustand kann nicht verhindert werden.
        /// </summary>
        internal static string HibernationNotBlocked {
            get {
                return ResourceManager.GetString("HibernationNotBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Schlafzustand kann nicht erlaubt werden.
        /// </summary>
        internal static string HibernationNotUnblocked {
            get {
                return ResourceManager.GetString("HibernationNotUnblocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Auftrag {0} wird aktualisiert.
        /// </summary>
        internal static string Information_JobUpgrade {
            get {
                return ResourceManager.GetString("Information_JobUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVB.NET Geräteprofil &apos;{0}&apos; nicht gefunden.
        /// </summary>
        internal static string InternalError_NoProfile {
            get {
                return ResourceManager.GetString("InternalError_NoProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Enddatum darf keine Uhrzeit enthalten.
        /// </summary>
        internal static string LastDayNotDate {
            get {
                return ResourceManager.GetString("LastDayNotDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Geräteprofile werden geladen: {0}.
        /// </summary>
        internal static string LoadProfiles {
            get {
                return ResourceManager.GetString("LoadProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es gibt kein Geräteprofil &apos;{0}&apos;.
        /// </summary>
        internal static string NoProfile {
            get {
                return ResourceManager.GetString("NoProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Aufzeichnungen vorhanden.
        /// </summary>
        internal static string NoSchedules {
            get {
                return ResourceManager.GetString("NoSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn einem Auftrag keine Quelle zugeordnet ist, so müssen alle Aufzeichnungen eine solche festlegen..
        /// </summary>
        internal static string NoTVStation {
            get {
                return ResourceManager.GetString("NoTVStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Liste der Quellen wird ersetzt.
        /// </summary>
        internal static string PSIReplace {
            get {
                return ResourceManager.GetString("PSIReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufzeichnung oder Aktualisierung {0} abgeschlossen.
        /// </summary>
        internal static string RecordingFinished {
            get {
                return ResourceManager.GetString("RecordingFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufzeichnung oder Aktualisierung {0} wird gestartet.
        /// </summary>
        internal static string RecordingStarted {
            get {
                return ResourceManager.GetString("RecordingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das DVB.NETGerät wird neu gestartet.
        /// </summary>
        internal static string RestartMessage {
            get {
                return ResourceManager.GetString("RestartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start der Erweiterung {0}.
        /// </summary>
        internal static string RunExtension {
            get {
                return ResourceManager.GetString("RunExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datei zum Auftrag {0} kann nicht geschrieben werden.
        /// </summary>
        internal static string SaveJobFailed {
            get {
                return ResourceManager.GetString("SaveJobFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Aufwecksignal wird aktiviert.
        /// </summary>
        internal static string StartWaitableTimer {
            get {
                return ResourceManager.GetString("StartWaitableTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schlafzustand unterbunden da noch mindestens ein Anwender am Rechner interaktiv angemeldet ist.
        /// </summary>
        internal static string UserActive {
            get {
                return ResourceManager.GetString("UserActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Server neu gestartet - dadurch kann die Systembelastung unnötig ansteigen.
        /// </summary>
        internal static string WebServerReload {
            get {
                return ResourceManager.GetString("WebServerReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Web Server wurde gestartet.
        /// </summary>
        internal static string WebServerStarted {
            get {
                return ResourceManager.GetString("WebServerStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Web Server konnte nicht beendet werden.
        /// </summary>
        internal static string WebServerStopFailed {
            get {
                return ResourceManager.GetString("WebServerStopFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die HTTP Verbindung konnte nicht beendet werden.
        /// </summary>
        internal static string WebServerStopFailedChannel {
            get {
                return ResourceManager.GetString("WebServerStopFailedChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Web Server wurde beendet.
        /// </summary>
        internal static string WebServerStopped {
            get {
                return ResourceManager.GetString("WebServerStopped", resourceCulture);
            }
        }
    }
}
