//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVBNETAdmin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DVBNETAdmin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        internal static string Button_Finish {
            get {
                return ResourceManager.GetString("Button_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVB.NET Configuration Manager.
        /// </summary>
        internal static string Caption_NoPlugIn {
            get {
                return ResourceManager.GetString("Caption_NoPlugIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string Caption_PlugIn {
            get {
                return ResourceManager.GetString("Caption_PlugIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the DVB.NET 3.9ff Profile to use.
        /// </summary>
        internal static string Navigation_Select1Profile {
            get {
                return ResourceManager.GetString("Navigation_Select1Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the DVB.NET 3.9ff Profiles to use.
        /// </summary>
        internal static string Navigation_SelectNProfiles {
            get {
                return ResourceManager.GetString("Navigation_SelectNProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the DVB.NET Administration.
        /// </summary>
        internal static string Navigation_SelectTask {
            get {
                return ResourceManager.GetString("Navigation_SelectTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (You may choose a Profile).
        /// </summary>
        internal static string Profile_Optional {
            get {
                return ResourceManager.GetString("Profile_Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Select the Profile to use).
        /// </summary>
        internal static string Profile_Required {
            get {
                return ResourceManager.GetString("Profile_Required", resourceCulture);
            }
        }
    }
}
