//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JMS.DVB.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JMS.DVB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create Pipeline Component {0}: {1}.
        /// </summary>
        internal static string Exception_NoExtension {
            get {
                return ResourceManager.GetString("Exception_NoExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The legacy BDA Driver is no longer supported - please upgrade the Profile &apos;{0}&apos;.
        /// </summary>
        internal static string Exception_NoLongerSupported {
            get {
                return ResourceManager.GetString("Exception_NoLongerSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer limit reached: {0} requested, got only {1}.
        /// </summary>
        internal static string Exception_OutOfConsumers {
            get {
                return ResourceManager.GetString("Exception_OutOfConsumers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No Extension).
        /// </summary>
        internal static string Select_NoAction {
            get {
                return ResourceManager.GetString("Select_NoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No Device).
        /// </summary>
        internal static string Select_NoDevice {
            get {
                return ResourceManager.GetString("Select_NoDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing State to {1} for Consumer {2} on Stream {0}.
        /// </summary>
        internal static string Trace_Consumer_ChangeState {
            get {
                return ResourceManager.GetString("Trace_Consumer_ChangeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream {0} changes State to {1}.
        /// </summary>
        internal static string Trace_Consumer_FilterChange {
            get {
                return ResourceManager.GetString("Trace_Consumer_FilterChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Consumer is {0}.
        /// </summary>
        internal static string Trace_Consumer_Identifier {
            get {
                return ResourceManager.GetString("Trace_Consumer_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer {0} not known.
        /// </summary>
        internal static string Trace_Consumer_NoConsumer {
            get {
                return ResourceManager.GetString("Trace_Consumer_NoConsumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering Consumer of Type {1} for Stream {0}.
        /// </summary>
        internal static string Trace_Consumer_Register {
            get {
                return ResourceManager.GetString("Trace_Consumer_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reusing existing Stream Information.
        /// </summary>
        internal static string Trace_Consumer_RegisterReuse {
            get {
                return ResourceManager.GetString("Trace_Consumer_RegisterReuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing Consumer {1} from Stream {0}.
        /// </summary>
        internal static string Trace_Consumer_RemoveConsumer {
            get {
                return ResourceManager.GetString("Trace_Consumer_RemoveConsumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Consumers will be terminated.
        /// </summary>
        internal static string Trace_Consumer_StoppingAll {
            get {
                return ResourceManager.GetString("Trace_Consumer_StoppingAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Group Change forwarded.
        /// </summary>
        internal static string Trace_Tuner_Hardware {
            get {
                return ResourceManager.GetString("Trace_Tuner_Hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Group change to Group {0} on Location {1} requested.
        /// </summary>
        internal static string Trace_Tuner_Request {
            get {
                return ResourceManager.GetString("Trace_Tuner_Request", resourceCulture);
            }
        }
    }
}
